title: <p align="center"> Nishth Choubey </p>
logo: /assets/img/DP.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nishtha-choubey-704208113/">LinkedIn</a> |
  <a href="https://github.com/nishthac888">GitHub</a>
  
  <br>   
  I'm working as Business Intel Engineer with Amazon
  <br>
  </p>



theme: jekyll-theme-minimal
